development:
  openroute_api_key: 5b3ce3597851110001cf6248d92d289171074188ade9c69501a27214

production:
  openroute_api_key: 5b3ce3597851110001cf6248d92d289171074188ade9c69501a27214

development:
  yelp_api_key: <your_yelp_api_key>

production:
  yelp_api_key: <your_yelp_api_key>

development:
  foursquare_api_key: <your_foursquare_api_key>

production:
  foursquare_api_key: <your_foursquare_api_key>