version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:3.1.4-node
    working_directory: ~/repo

jobs:
  test:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - test