version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:3.1.4-node-browsers

jobs:
  build:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec

  deploy:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build